title: "NeurIPS 2024 Acceptance & Rejection Analysis"
description: "A meta-scientific study on topics, math complexity, novelty, and review patterns in NeurIPS papers."
theme: jekyll-theme-cayman
markdown: kramdown
