title: "Fundamental Research Space"
description: "Generative AI Research Blog"
theme: jekyll-theme-cayman

markdown: kramdown
permalink: pretty

# Navigation links (top menu)
nav:
  - title: "Home"
    url: /
  - title: "Research Blog"
    url: /research/
  - title: "About"
    url: /about/
