title: "Aarti's Research Space"
description: "NeurIPS Analysis, AI Research Blog, Philosophy Notes, and More."
theme: jekyll-theme-cayman

markdown: kramdown
permalink: pretty

# Navigation links (top menu)
nav:
  - title: "Home"
    url: /
  - title: "Research Blog"
    url: /research/
  - title: "Philosophy"
    url: /philosophy/
  - title: "About"
    url: /about/
